const express=require('express');const cors=require('cors');const multer=require('multer');const path=require('path');const fs=require('fs');const sharp=require('sharp');const {execFile}=require('child_process');const ffmpeg=require('ffmpeg-static');const ffprobe=require('ffprobe-static').path;require('dotenv').config();
const app=express();
const configuredOrigins=String(process.env.CORS_ORIGIN||'http://localhost:5173,http://localhost:4173').split(',').map(x=>x.trim()).filter(Boolean);
const allowedOrigins=configuredOrigins.includes('*')?['http://localhost:5173','http://127.0.0.1:5173','http://localhost:4173','http://127.0.0.1:4173','http://localhost:3000','http://127.0.0.1:3000']:configuredOrigins;
app.use(cors({origin:(origin,callback)=>!origin||allowedOrigins.includes(origin)?callback(null,true):callback(new Error('Origin không được phép')),credentials:true,methods:['GET','POST','PUT','PATCH','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization']}));
async function requireAuth(req,res,next){try{const response=await fetch(`${process.env.CHAT_SERVER_URL||'http://localhost:3000'}/api/auth/me`,{headers:{cookie:req.headers.cookie||''}});if(!response.ok)return res.status(401).json({error:'Chưa đăng nhập'});req.user=await response.json();return next();}catch(error){console.error('Media auth error:',error.message);return res.status(503).json({error:'Không thể xác thực phiên'});}}
const dir=path.resolve(process.env.UPLOAD_DIR||'./uploads');fs.mkdirSync(dir,{recursive:true});app.use('/media',express.static(dir));
const max=Number(process.env.MAX_FILE_MB||200)*1024*1024;const storage=multer.diskStorage({destination:(req,f,cb)=>cb(null,dir),filename:(req,f,cb)=>cb(null,`${Date.now()}_${Math.random().toString(36).slice(2,10)}${path.extname(f.originalname).toLowerCase()}`)});const upload=multer({storage,limits:{fileSize:max}});
function probe(p){return new Promise((resolve,reject)=>execFile(ffprobe,['-v','error','-show_entries','format=duration:stream=width,height','-of','json',p],(e,out)=>e?reject(e):resolve(JSON.parse(out))));}
app.get('/',(req,res)=>res.json({service:'media-server',status:'ok'}));app.get('/health',(req,res)=>res.json({ok:true,storage:process.env.STORAGE_MODE||'local'}));
app.post('/api/upload',requireAuth,upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Thiếu file'});const isVideo=req.file.mimetype.startsWith('video/');const isImage=req.file.mimetype.startsWith('image/');let thumb=null,width=null,height=null,duration=null;if(isImage){const t=`thumb_${path.parse(req.file.filename).name}.jpg`;await sharp(req.file.path).resize(640,640,{fit:'inside',withoutEnlargement:true}).jpeg({quality:75}).toFile(path.join(dir,t));thumb=`${process.env.MEDIA_BASE_URL||''}/media/${t}`;const meta=await sharp(req.file.path).metadata();width=meta.width||null;height=meta.height||null;}if(isVideo){const meta=await probe(req.file.path);duration=Math.round(Number(meta.format?.duration)||0);const stream=(meta.streams||[]).find(x=>x.width&&x.height);width=stream?.width||null;height=stream?.height||null;const t=`thumb_${path.parse(req.file.filename).name}.jpg`;await new Promise((resolve,reject)=>execFile(ffmpeg,['-y','-ss','0','-i',req.file.path,'-frames:v','1','-vf','scale=640:-2','-q:v','5',path.join(dir,t)],e=>e?reject(e):resolve()));thumb=`${process.env.MEDIA_BASE_URL||''}/media/${t}`;}
res.json({success:true,attachment:{attachment_type:isVideo?'video':isImage?'image':'file',file_name:req.file.originalname,file_url:`${process.env.MEDIA_BASE_URL||''}/media/${req.file.filename}`,thumbnail_url:thumb,mime_type:req.file.mimetype,file_size:req.file.size,width,height,duration_sec:duration}});}catch(e){console.error(e);res.status(500).json({error:e.message});}});
app.use((e,req,res,next)=>res.status(400).json({error:e.message}));app.listen(Number(process.env.PORT||3002),'0.0.0.0',()=>console.log(`Media server listening on ${process.env.PORT||3002}`));
